server:
  port: 8080
  servlet:
    context-path: /searanch
  tomcat:
    uri-encoding: UTF-8
management:  #actuator
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
spring:
  datasource:
    username: root
    password: lhd021412
    url: jdbc:mysql://47.115.141.255:3306/searanch?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    min-evictable-idle-time-millis: 300000
    filters: stat,wall,log4j
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
  mvc:
    static-path-pattern: /webapp/**
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
  redis:
    host: 47.115.141.255
    #password: admin
    port: 6379
    max-wait: 30000  #连接池最大阻塞等待时间
    max-active: 100  #连接池最大连接数
    max-idle: 10     #连接池中最大空闲连接
    min-idle: 0      #连接池中的最小空闲连接
    timeout: 6000    #连接超时
  mail:
    host: smtp.126.com
    username: luohuiduo@126.com
    password: JHNXGLRIDYMMXFCK
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
file:
  staticAccessPath: /static/image/**
  uploadFolder: C://image/
mybatis:
  type-aliases-package: com.yunyuan.searanch.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  config: classpath:logback.xml
